import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";
import "./globals.css";
import { ThemeProvider } from "next-themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hexleap",
  description: "Generated by create next app for hexleap.",
  icons: {
    icon: ["/favicon.ico"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const description = metadata.description || ""; // Ensure description is not null
  const title = metadata.title || ""; // Ensure title is not null
  return (
    <ThemeProvider enableSystem={true} attribute="class">
      <Head>
        x<title>{String(title)}</title> {/* Convert title to string */}
        <meta name="description" content={description} />
        
      </Head>
      <body className={`${inter.className}`}>{children}</body>
    </ThemeProvider>
  );
}
